[package]
name = "toydb"
version = "0.1.0"
authors = ["Shaun Mangelsdorf <s.mangelsdorf@gmail.com>"]
edition = "2018"

[dependencies]
nom = "^6"

[lib]
name = "toydb"

[[bin]]
name = "toydb"

[[bin]]
name = "toydb-cli"
